
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird crash_course_kore - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
    jobs:
      cd:  # deploy changes to workspace 'crash_course_kore'
        uses: tinybirdco/ci/.github/workflows/cd.yml@v3.1.0
        with:
          data_project_dir: .
        secrets:
          tb_admin_token: ${{ secrets.TB_CRASH_COURSE_KORE_ADMIN_TOKEN }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://ui.us-east.tinybird.co
